#!/usr/bin/python

import sys, os, signal

pipe_name = None
grandparent = None

def remove_pipe():
  try:
    os.unlink(pipe_name)
  except:
    return False
  return True

def process_file(file_name):
  if pipe_name is None:
    raise Exception('show: no pipe name')
  if grandparent is None:
     raise Exception('show: granparent process not found')
  try:
    fd = open(file_name, "rb")
  except:
    remove_pipe()
    raise Exception('show: problem while opening file' + file_name)
  if not fd:
    remove_pipe()
    raise Exception('show: problem with file descriptor')
  try:
     os.kill(grandparent, signal.SIGUSR1)
     pipe = open(pipe_name, "wb")
  except:
     remove_pipe()
     raise Exception('show: problem while opening pipe')
  line = fd.read()
  while len(line):
        print >> pipe, line
        line = fd.read()
  print >> pipe, line
  fd.close()
  pipe.flush()
  if not pipe.closed: pipe.close()

def process_stdin():
  if pipe_name is None:
     raise Exception('show: no pipe name')
  if grandparent is None:
     raise Exception('show: grandparent process not found')
  if sys.stdin.isatty():
    remove_pipe()
    raise Exception('show: terminal input is not supported')
  try:
     os.kill(grandparent, signal.SIGUSR1)
     pipe = open(pipe_name, "wb")
  except:
     remove_pipe()
     raise Exception('show: cannot open named pipe')
  print >> pipe, sys.stdin.read()
  pipe.flush()
  if not pipe.closed: pipe.close()

def main():
   argv = sys.argv
   if len(argv) < 2:
      try_pipe = True
   else:
      try_pipe = False
   parentpid = os.getppid()
   if parentpid < 1:
     return
   global pipe_name
   pipe_name = "/tmp/pipe_show_%s" % str(parentpid)
   if os.path.exists(pipe_name):
     if not remove_pipe():
       print >> sys.stderr, ("show: pipe " + pipe_name + " cannot be not removed") 
       return
   termpy_file = "/tmp/show_gppid_%s"  % (parentpid)
   global grandparent
   try:
     with open(termpy_file, "r") as f:
        grandparent = int(f.readline())
   except:
      print >> sys.stderr, ("show: lock file problem: " + termpy_file)
      return
   if not os.path.exists(pipe_name):
      try:
        os.mkfifo(pipe_name)
      except:
        print >> sys.stderr, "show: cannot create pipe"
        return
      try:
        if not try_pipe:
          process_file(argv[1])
        else:
          process_stdin()
      except Exception as exception:
        print >> sys.stderr, exception

if __name__=='__main__':
  main()
